version: '2'

services:
    couchbase:
        image: couchbase-custom
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
            - 11210:11210
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_USER=Nodejs
            - COUCHBASE_BUCKET_PASSWORD=couchbase

    nodejs:
        image: nodejs-custom
        ports:
            - 3000:3000
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_USER=Nodejs
            - COUCHBASE_BUCKET_PASSWORD=couchbase
            - APPLICATION_PORT=3000
        restart: always